export const json = {
    title: "PBL 5",
    description: "Muhammad Daffa Rudiyanto (Student ID: 26002104783) Ver. 4",
    logoPosition: "right",
    pages: [
        {
            name: "introduction",
            elements: [
                {
                    type: "html",
                    name: "question36",
                    html: "<p>\nDear Participant,\n<br>\n<br>\nWe would like to invite you to take part in a fascinating survey that explores the auditory experience of electric vehicles. As the world shifts towards greener transportation options, electric vehicles are becoming increasingly common on our roads. However, these vehicles operate differently from traditional internal combustion engine cars, emitting unique sounds or, in some cases, running silently. In this survey, we aim to gather valuable insights into how people perceive and respond to various sound profiles emitted by electric vehicles as they pass by. Your participation will contribute to our understanding of the impact of sound on road safety and public acceptance of electric vehicles. Thank you for joining us on this exciting exploration of sound and transportation!\n</p>",
                },
            ],
            title: "Introduction",
        },
        {
            name: "demographic",
            elements: [
                {
                    type: "radiogroup",
                    name: "question1",
                    title: "Age",
                    isRequired: true,
                    choices: [
                        {
                            value: "Item 1",
                            text: "< 18 years old",
                        },
                        {
                            value: "Item 2",
                            text: "18 - 25 years old",
                        },
                        {
                            value: "Item 3",
                            text: "26 - 39 years old",
                        },
                        {
                            value: "Item 4",
                            text: "40 - 60 years old",
                        },
                        {
                            value: "Item 5",
                            text: "> 60 years old",
                        },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "question2",
                    title: "Gender",
                    isRequired: true,
                    choices: [
                        {
                            value: "Item 1",
                            text: "Male",
                        },
                        {
                            value: "Item 2",
                            text: "Female",
                        },
                        {
                            value: "Item 3",
                            text: "Others",
                        },
                        {
                            value: "Item 4",
                            text: "Prefer not to answer",
                        },
                    ],
                },
            ],
            title: "Demographic Question",
        },
        {
            name: "sound1",
            elements: [
                {
                    type: "html",
                    name: "song1",
                    html: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0XQHpt64EzE\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },

                {
                    type: "radiogroup",
                    name: "question3",
                    title: "Do you hear the sound?",
                    isRequired: true,
                    choices: [
                        {
                            value: "Item 1",
                            text: "Yes",
                        },
                        {
                            value: "Item 2",
                            text: "No",
                        },
                    ],
                },
                {
                    type: "rating",
                    name: "question4",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "Sound Awareness",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Not aware at all",
                    maxRateDescription: "Very aware",
                },
                {
                    type: "rating",
                    name: "question5",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "Calm or Panic?",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Calm",
                    maxRateDescription: "Panic",
                },
                {
                    type: "rating",
                    name: "question6",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "Comfortable or Scared",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Comfortable",
                    maxRateDescription: "Scared",
                },
                {
                    type: "rating",
                    name: "question7",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "Pleasant or Annoying",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Pleasant",
                    maxRateDescription: "Annoying",
                },
                {
                    type: "rating",
                    name: "question8",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "Relax or Nervous",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Relax",
                    maxRateDescription: "Nervous",
                },
                {
                    type: "rating",
                    name: "question9",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "Focus or Distracted",
                    isRequired: true,
                    minRateDescription: "Focus",
                    maxRateDescription: "Distracted",
                },
                {
                    type: "rating",
                    name: "question10",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "Obedient or Attacked",
                    isRequired: true,
                    minRateDescription: "Obedient",
                    maxRateDescription: "Attack",
                },
                {
                    type: "rating",
                    name: "question11",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "How far is the sound?",
                    isRequired: true,
                    minRateDescription: "Near",
                    maxRateDescription: "Far",
                },
                {
                    type: "rating",
                    name: "question12",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "How loud is the sound?",
                    isRequired: true,
                    minRateDescription: "Quite",
                    maxRateDescription: "Loud",
                },
                {
                    type: "rating",
                    name: "question13",
                    visibleIf: "{question3} = 'Item 1'",
                    title: "How big is the vehicle?",
                    isRequired: true,
                    minRateDescription: "Small",
                    maxRateDescription: "Big",
                },
            ],
            title: "Sound 1",
        },
        {
            name: "sound2",
            elements: [
                {
                    type: "radiogroup",
                    name: "question14",
                    title: "Do you hear the sound?",
                    isRequired: true,
                    choices: [
                        {
                            value: "Item 1",
                            text: "Yes",
                        },
                        {
                            value: "Item 2",
                            text: "No",
                        },
                    ],
                },
                {
                    type: "rating",
                    name: "question15",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "Sound Awareness",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Not aware at all",
                    maxRateDescription: "Very aware",
                },
                {
                    type: "rating",
                    name: "question16",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "Calm or Panic?",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Calm",
                    maxRateDescription: "Panic",
                },
                {
                    type: "rating",
                    name: "question17",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "Comfortable or Scared",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Comfortable",
                    maxRateDescription: "Scared",
                },
                {
                    type: "rating",
                    name: "question18",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "Pleasant or Annoying",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Pleasant",
                    maxRateDescription: "Annoying",
                },
                {
                    type: "rating",
                    name: "question19",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "Relax or Nervous",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Relax",
                    maxRateDescription: "Nervous",
                },
                {
                    type: "rating",
                    name: "question20",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "Focus or Distracted",
                    isRequired: true,
                    minRateDescription: "Focus",
                    maxRateDescription: "Distracted",
                },
                {
                    type: "rating",
                    name: "question21",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "Obedient or Attacked",
                    isRequired: true,
                    minRateDescription: "Obedient",
                    maxRateDescription: "Attack",
                },
                {
                    type: "rating",
                    name: "question22",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "How far is the sound?",
                    isRequired: true,
                    minRateDescription: "Near",
                    maxRateDescription: "Far",
                },
                {
                    type: "rating",
                    name: "question23",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "How loud is the sound?",
                    isRequired: true,
                    minRateDescription: "Quite",
                    maxRateDescription: "Loud",
                },
                {
                    type: "rating",
                    name: "question24",
                    visibleIf: "{question14} = 'Item 1'",
                    title: "How big is the vehicle?",
                    isRequired: true,
                    minRateDescription: "Small",
                    maxRateDescription: "Big",
                },
            ],
            title: "Sound 2",
        },
        {
            name: "sound3",
            elements: [
                {
                    type: "radiogroup",
                    name: "question25",
                    title: "Do you hear the sound?",
                    isRequired: true,
                    choices: [
                        {
                            value: "Item 1",
                            text: "Yes",
                        },
                        {
                            value: "Item 2",
                            text: "No",
                        },
                    ],
                },
                {
                    type: "rating",
                    name: "question26",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "Sound Awareness",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Not aware at all",
                    maxRateDescription: "Very aware",
                },
                {
                    type: "rating",
                    name: "question27",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "Calm or Panic?",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Calm",
                    maxRateDescription: "Panic",
                },
                {
                    type: "rating",
                    name: "question28",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "Comfortable or Scared",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Comfortable",
                    maxRateDescription: "Scared",
                },
                {
                    type: "rating",
                    name: "question29",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "Pleasant or Annoying",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Pleasant",
                    maxRateDescription: "Annoying",
                },
                {
                    type: "rating",
                    name: "question30",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "Relax or Nervous",
                    isRequired: true,
                    autoGenerate: false,
                    rateValues: [1, 2, 3, 4, 5],
                    minRateDescription: "Relax",
                    maxRateDescription: "Nervous",
                },
                {
                    type: "rating",
                    name: "question31",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "Focus or Distracted",
                    isRequired: true,
                    minRateDescription: "Focus",
                    maxRateDescription: "Distracted",
                },
                {
                    type: "rating",
                    name: "question32",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "Obedient or Attacked",
                    isRequired: true,
                    minRateDescription: "Obedient",
                    maxRateDescription: "Attack",
                },
                {
                    type: "rating",
                    name: "question33",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "How far is the sound?",
                    isRequired: true,
                    minRateDescription: "Near",
                    maxRateDescription: "Far",
                },
                {
                    type: "rating",
                    name: "question34",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "How loud is the sound?",
                    isRequired: true,
                    minRateDescription: "Quite",
                    maxRateDescription: "Loud",
                },
                {
                    type: "rating",
                    name: "question35",
                    visibleIf: "{question25} = 'Item 1'",
                    title: "How big is the vehicle?",
                    isRequired: true,
                    minRateDescription: "Small",
                    maxRateDescription: "Big",
                },
            ],
            title: "Sound 3",
        },
    ],
};
